variables:
  BASEVERSION: 1.0.1
  VERSION: ${BASEVERSION}.${CI_PIPELINE_ID}.${CI_COMMIT_BRANCH}
  IMAGE_NAME: carrier_dev
  
stages:
  - build
  
build-job:
  stage: build
  script:
    - echo "Hello, $GITLAB_USER_LOGIN!"
    - echo "Deploy Branch $CI_COMMIT_BRANCH."
