image: gitlab/dind
services:
  - docker:dind
  - mysql:latest

variables:
  DOCKER_DRIVER: overlay
  SPRING_PROFILES_ACTIVE: gitlab-ci
  APP_NAME: carrier
  REPO: carrier
  MYSQL_DATABASE: $MYSQL_DATABASE
  MYSQL_ROOT_PASSWORD: $MYSQL_PASSWORD
  IMAGE_NAME: reseller-carrier-data

stages:
  - build
  - test
  - docker

maven-build:
  image: maven:3-jdk-8
  stage: build
  script: "mvn clean package -B"
  artifacts:
    paths:
      - target/*.jar

maven-test:
  image: maven:3-jdk-8
  stage: test
  script:
    - 'mvn test'
  artifacts:
    paths:
      - target/*.jar

docker-build:
  stage: docker
  tags: 
    - otc_run_docker_s
  image: docker:latest
  script:
    - docker login -u gitlab-ci-token -p $CI_JOB_TOKEN $CI_REGISTRY
    - docker build -t registry.devops.telekom.de/thomas.wolff/carriers .
    - docker push registry.devops.telekom.de/thomas.wolff/carriers
