version: '3.7'
services:
  mysqlserver:
    image: mysql:8.0.23
    ports:
      - 3306:3306
    environment:
      - MYSQL_ROOT_PASSWORD=
      - MYSQL_ALLOW_EMPTY_PASSWORD=true
      - MYSQL_USER=thomas
      - MYSQL_PASSWORD=uzgTrfEa
      - MYSQL_DATABASE=jpa_carrier
    volumes:
      - mysql_data:/var/lib/mysql
      - mysql_config:/etc/mysql/conf.d
    networks:
      - my-network

  carrier:
    image: registry.devops.telekom.de/thomas.wolff/carriers:latest
    depends_on:
      - mysqlserver
    ports:
      - 8080:8080
    environment:
      - SERVER_PORT=8080
      - MYSQL_USER=thomas
      - MYSQL_PASSWORD=uzgTrfEa
      - MYSQL_URL=jdbc:mysql://mysqlserver/jpa_carrier
    volumes:
      - ./:/app
    networks:
      - my-network


volumes:
  mysql_data:
  mysql_config:
networks:
  my-network: {}
