kind: Namespace
apiVersion: v1
metadata:
  name: carrier-app
  selfLink: /api/v1/namespaces/carrier-app
  uid: d4852103-e975-4bfe-ac2d-505c727d4f83
  resourceVersion: '55500'
  creationTimestamp: '2021-05-09T19:08:21Z'
  annotations:
    openshift.io/description: ''
    openshift.io/display-name: carrier
    openshift.io/requester: developer
    openshift.io/sa.scc.mcs: 's0:c25,c15'
    openshift.io/sa.scc.supplemental-groups: 1000630000/10000
    openshift.io/sa.scc.uid-range: 1000630000/10000
  managedFields:
    - manager: cluster-policy-controller
      operation: Update
      apiVersion: v1
      time: '2021-05-09T19:08:21Z'
      fieldsType: FieldsV1
      fieldsV1:
        'f:metadata':
          'f:annotations':
            'f:openshift.io/sa.scc.mcs': {}
            'f:openshift.io/sa.scc.supplemental-groups': {}
            'f:openshift.io/sa.scc.uid-range': {}
    - manager: openshift-apiserver
      operation: Update
      apiVersion: v1
      time: '2021-05-09T19:08:21Z'
      fieldsType: FieldsV1
      fieldsV1:
        'f:metadata':
          'f:annotations':
            .: {}
            'f:openshift.io/description': {}
            'f:openshift.io/display-name': {}
            'f:openshift.io/requester': {}
        'f:status':
          'f:phase': {}
    - manager: openshift-controller-manager
      operation: Update
      apiVersion: v1
      time: '2021-05-09T19:08:21Z'
      fieldsType: FieldsV1
      fieldsV1:
        'f:spec':
          'f:finalizers': {}
spec:
  finalizers:
    - kubernetes
status:
  phase: Active
