kind: Service
apiVersion: v1
metadata:
  annotations:
    template.openshift.io/expose-uri: 'mysql://{.spec.clusterIP}:{.spec.ports[?(.name=="mysql")].port}'
  selfLink: /api/v1/namespaces/carrier-project/services/mysql
  resourceVersion: '40225'
  name: mysql
  uid: 341ced27-3f01-446f-8650-42923287dcc6
  creationTimestamp: '2021-05-09T17:42:31Z'
  managedFields:
    - manager: openshift-controller-manager
      operation: Update
      apiVersion: v1
      time: '2021-05-09T17:42:31Z'
      fieldsType: FieldsV1
      fieldsV1:
        'f:metadata':
          'f:annotations':
            .: {}
            'f:template.openshift.io/expose-uri': {}
          'f:labels':
            .: {}
            'f:template': {}
            'f:template.openshift.io/template-instance-owner': {}
        'f:spec':
          'f:ports':
            .: {}
            'k:{"port":3306,"protocol":"TCP"}':
              .: {}
              'f:name': {}
              'f:port': {}
              'f:protocol': {}
              'f:targetPort': {}
          'f:selector':
            .: {}
            'f:name': {}
          'f:sessionAffinity': {}
          'f:type': {}
  namespace: carrier-project
  labels:
    template: mysql-persistent-template
    template.openshift.io/template-instance-owner: cbb11ed8-4022-41f3-ac3e-5753614e8b7c
spec:
  ports:
    - name: mysql
      protocol: TCP
      port: 3306
      targetPort: 3306
  selector:
    name: mysql
  clusterIP: 10.217.4.123
  clusterIPs:
    - 10.217.4.123
  type: ClusterIP
  sessionAffinity: None
status:
  loadBalancer: {}
